### ISSUE TITLE
'datasheet' needs to show as an Item

### ISSUE THREAD

**Issue by barrowisp** [barrowisp/craftastrophe#2]
First idea for #1 is to create an item, which looks similar to 'vanilla' paper (as seen in 1.12.2), and behaves similar to a treasure map (as seen in 1.13.2)
For now, I'm calling it a 'datasheet', based on this definition:

>  A _datasheet_, _data sheet_, or _spec sheet_ is a document that summarizes the performance and other technical characteristics of a product, machine, component, material, a subsystem or software in sufficient detail that allows design engineer to understand the role of the component in the overall system.

It could also be called a _technical document_, or some derivative of that.  'Blueprint' is used by ImmersiveEngineering and I need to check what it does.  'Redprint' is used by... I think it's ThermalFoundation, and it's specifically for copying configurations from one block to another, not at all what I have in mind.  So I want to stay away from those two, but a different color should be fine.  'Whiteprint' isn't as informative as 'datasheet' though, which has the benefit of being a real thing.

**Comment by yooksi** [comment]
That sounds, good but wouldn't we use these ```datasheets``` to also implement limitations for displaying more primitive recipes like building a small wooden raft? In that case it would not be an appropriate name. Datasheet can be a type of print that is used to display more technologically advanced blueprints.

**Comment by yooksi** [comment]
I've decided to call the class ```Blueprint``` but the in-game name is defined in the language file so we can change that whenever we want to. Currently the in-game name is ```Crafting Plan``` which should be generic enough to encompass both primitive and advanced technology. 

Once picked up the item could be replaced with a different subclass of it like a ```datasheet```. For example if we were to introduce simple skills at one point, then if the player doesn't have enough *knowledge* the item would appear like a crafting plan until he demystifies it.
