### ISSUE TITLE
Replace vanilla texture for Blueprint with a custom texture

### ISSUE THREAD

**Issue by barrowisp** [barrowisp/craftastrophe#30]
- [x] make a texture other than plain white
- [x] determine how to reference the texture file within the code
- [x] poll other developers about the degree of difference needed (between Mojang textures and my variant) to avoid copyright infringement
- [ ] make a truly original texture
- [x] commit the image file
- [x] update the code to reference the new texture file

**Comment by barrowisp** [comment]
inside the item's json file, add this: 
``` 
"textures": {
    "layer0": "craftastrophe:blueprint"
  }
```

**Comment by yooksi** [comment]
Concerning any copyrighting infringement, you can read their [BRAND AND ASSET USAGE GUIDELINES](https://account.mojang.com/documents/brand_guidelines). This is taken from their statement on creating game content for non-commercial purposes: 

>We are very relaxed about things you create for yourself. Pretty much anything goes there - so go for it, have fun, and just don't distribute anything we've made.

>We are also quite relaxed about other non-commercial things so feel free to create and share videos, screen shots, independently created mods (that don't use any of our Assets), fan art, machinima, etc.```

**Comment by barrowisp** [comment]
Changed vanilla Paper to light blue
